apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  labels:
    app: todo
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      tier: frontend
  template:
    metadata:
      labels:
        app: todo
        tier: frontend
    spec:
      containers:
      - name: todo-frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
           path: /
           port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
