apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  labels:
    app: todo
    tier: frontend
spec:
  selector:
    app: todo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
