apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  labels:
    app: todo
    tier: api
spec:
  selector:
    app: todo
    tier: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
