# Default values for todo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
database: 
  host: ""
  username: ""
  password: ""

environment: production

api:
  image:
    repository: ""
    tag: ""
frontend:
  image:
    repository: ""
    tag: ""
